[package]
name = "visualwav"
version = "0.1.0"
authors = ["Will Greenberg <willg@eff.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.74"
console_error_panic_hook = "0.1.6"
rustfft = "6.0.1"
hound = "3.4.0"
